import { notFound } from "next/navigation";
import Link from "next/link";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import { CopyButton } from "@/components/copy-button";

export const dynamic = "force-dynamic";

interface ArchResult {
  summary: string;
  tools: Array<{ name: string; category: string; reason: string }>;
  diagram: string;
  buildSteps: string[];
  tradeoffs: string[];
}

interface SharedStack {
  id: string;
  prompt: string;
  result: ArchResult;
  createdAt: string;
}

function buildMarkdown(prompt: string, result: ArchResult): string {
  return `# Architecture: ${prompt}

## Summary
${result.summary}

## Recommended Stack
${result.tools.map((t) => `- **${t.name}** (${t.category}): ${t.reason}`).join("\n")}

## Architecture Diagram
\`\`\`mermaid
${result.diagram}
\`\`\`

## Build Steps
${result.buildSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

## Tradeoffs
${result.tradeoffs.map((t) => `- ${t}`).join("\n")}

---
Generated by [AI Stack Radar](https://ai-stack-radar.vercel.app)
`;
}

async function getStack(id: string): Promise<SharedStack | null> {
  try {
    const { db } = await import("@/lib/db");
    const { sharedStacks } = await import("@/lib/schema");
    const { eq } = await import("drizzle-orm");

    const [stack] = await db
      .select()
      .from(sharedStacks)
      .where(eq(sharedStacks.id, id))
      .limit(1);

    if (!stack) return null;

    return {
      id: stack.id,
      prompt: stack.prompt,
      result: stack.result as ArchResult,
      createdAt: stack.createdAt.toISOString(),
    };
  } catch {
    return null;
  }
}

export default async function SharedStackPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const stack = await getStack(id);

  if (!stack) {
    notFound();
  }

  const result = stack.result;
  const markdown = buildMarkdown(stack.prompt, result);

  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <div className="mb-8 flex items-start justify-between gap-4">
        <div>
          <p className="text-sm text-zinc-500 mb-2">Shared Stack</p>
          <h1 className="text-2xl font-bold tracking-tight">{stack.prompt}</h1>
        </div>
        <CopyButton text={markdown} label="Copy all" />
      </div>

      <div className="space-y-8">
        {/* Summary */}
        <div className="p-5 rounded-xl border border-zinc-800 bg-zinc-900/30">
          <p className="text-zinc-300 leading-relaxed">{result.summary}</p>
        </div>

        {/* Recommended tools */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold">Recommended Stack</h2>
            <CopyButton
              text={result.tools
                .map((t) => `${t.name} (${t.category}): ${t.reason}`)
                .join("\n")}
            />
          </div>
          <div className="grid gap-3">
            {result.tools.map((tool, i) => (
              <div
                key={i}
                className="p-4 border border-zinc-800 rounded-xl bg-zinc-900/30"
              >
                <div className="flex items-center gap-3 mb-1.5">
                  <span className="font-medium text-zinc-100">{tool.name}</span>
                  <span className="text-xs px-2 py-0.5 rounded-md bg-zinc-800 text-zinc-400">
                    {tool.category}
                  </span>
                </div>
                <p className="text-sm text-zinc-400 leading-relaxed">{tool.reason}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Diagram — rendered client-side via Mermaid */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold">Architecture Diagram</h2>
            <CopyButton text={`\`\`\`mermaid\n${result.diagram}\n\`\`\``} label="Copy" />
          </div>
          <MermaidDiagram chart={result.diagram} />
        </div>

        {/* Build Steps */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold">Build Steps</h2>
            <CopyButton
              text={result.buildSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}
            />
          </div>
          <ol className="space-y-3">
            {result.buildSteps.map((step, i) => (
              <li key={i} className="flex gap-3">
                <span className="flex-shrink-0 w-7 h-7 rounded-full bg-zinc-800 flex items-center justify-center text-sm font-medium text-zinc-400">
                  {i + 1}
                </span>
                <span className="text-zinc-300 pt-0.5 leading-relaxed">{step}</span>
              </li>
            ))}
          </ol>
        </div>

        {/* Tradeoffs */}
        <div>
          <h2 className="text-lg font-semibold mb-4">Tradeoffs</h2>
          <ul className="space-y-2">
            {result.tradeoffs.map((tradeoff, i) => (
              <li
                key={i}
                className="text-zinc-400 text-sm pl-4 border-l-2 border-zinc-700 leading-relaxed"
              >
                {tradeoff}
              </li>
            ))}
          </ul>
        </div>

        {/* Footer CTA */}
        <div className="pt-8 border-t border-zinc-800 text-center">
          <p className="text-zinc-500 text-sm mb-3">
            Generated by AI Stack Radar — architecture recommendations backed by live
            sentiment data.
          </p>
          <Link
            href="/generate"
            className="px-6 py-2.5 bg-white text-zinc-900 rounded-lg font-medium hover:bg-zinc-200 transition-colors inline-block"
          >
            Generate Your Own Stack
          </Link>
        </div>
      </div>
    </div>
  );
}
