import { notFound } from "next/navigation";
import Link from "next/link";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import { CopyButton } from "@/components/copy-button";
import {
  isSharedArchitectureResult,
  type SharedArchitectureResult,
} from "@/lib/architecture";

export const dynamic = "force-dynamic";

interface SharedStack {
  id: string;
  prompt: string;
  result: SharedArchitectureResult;
  createdAt: string;
}

function buildMarkdown(prompt: string, result: SharedArchitectureResult): string {
  return `# Architecture: ${prompt}

## Summary
${result.summary}

## Recommended Stack
${result.tools.map((t) => `- **${t.name}** (${t.category}): ${t.reason}`).join("\n")}

## Architecture Diagram
\`\`\`mermaid
${result.diagram}
\`\`\`

## Build Steps
${result.buildSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

## Tradeoffs
${result.tradeoffs.map((t) => `- ${t}`).join("\n")}

---
Generated by [AI Stack Radar](https://ai-stack-radar.vercel.app)
`;
}

async function getStack(id: string): Promise<SharedStack | null> {
  try {
    const { db } = await import("@/lib/db");
    const { sharedStacks } = await import("@/lib/schema");
    const { eq } = await import("drizzle-orm");

    const [stack] = await db
      .select()
      .from(sharedStacks)
      .where(eq(sharedStacks.id, id))
      .limit(1);

    if (!stack) return null;
    if (!isSharedArchitectureResult(stack.result)) return null;

    return {
      id: stack.id,
      prompt: stack.prompt,
      result: stack.result,
      createdAt: stack.createdAt.toISOString(),
    };
  } catch {
    return null;
  }
}

export default async function SharedStackPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const stack = await getStack(id);

  if (!stack) {
    notFound();
  }

  const result = stack.result;
  const markdown = buildMarkdown(stack.prompt, result);

  return (
    <div className="max-w-4xl mx-auto px-6 py-12 animate-fade-in">
      <div className="mb-10 flex items-start justify-between gap-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest mb-3" style={{ color: "var(--text-tertiary)", fontFamily: "var(--font-syne), sans-serif", letterSpacing: "0.12em" }}>
            Shared Stack
          </p>
          <h1
            className="text-2xl font-bold tracking-tight"
            style={{ fontFamily: "var(--font-syne), sans-serif", letterSpacing: "-0.03em" }}
          >
            {stack.prompt}
          </h1>
        </div>
        <CopyButton text={markdown} label="Copy all" />
      </div>

      <div className="space-y-8">
        {/* Summary */}
        <div
          className="p-5 rounded-xl"
          style={{ background: "var(--bg-surface)", border: "1px solid var(--border-subtle)" }}
        >
          <p className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>{result.summary}</p>
        </div>

        {/* Recommended tools */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-bold" style={{ fontFamily: "var(--font-syne), sans-serif" }}>
              Recommended Stack
            </h2>
            <CopyButton
              text={result.tools
                .map((t) => `${t.name} (${t.category}): ${t.reason}`)
                .join("\n")}
            />
          </div>
          <div className="grid gap-3">
            {result.tools.map((tool, i) => (
              <div
                key={i}
                className="p-4 rounded-xl"
                style={{ background: "var(--bg-surface)", border: "1px solid var(--border-subtle)" }}
              >
                <div className="flex items-center gap-3 mb-2">
                  <span className="font-semibold text-sm" style={{ color: "var(--text-primary)", fontFamily: "var(--font-syne), sans-serif" }}>{tool.name}</span>
                  <span
                    className="text-xs px-2.5 py-0.5 rounded-lg"
                    style={{ background: "var(--accent-cyan-dim)", color: "var(--accent-cyan)", border: "1px solid rgba(34,211,238,0.2)", fontFamily: "var(--font-syne), sans-serif" }}
                  >
                    {tool.category}
                  </span>
                </div>
                <p className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>{tool.reason}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Diagram */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-bold" style={{ fontFamily: "var(--font-syne), sans-serif" }}>
              Architecture Diagram
            </h2>
            <CopyButton text={`\`\`\`mermaid\n${result.diagram}\n\`\`\``} label="Copy" />
          </div>
          <MermaidDiagram chart={result.diagram} />
        </div>

        {/* Build Steps */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-bold" style={{ fontFamily: "var(--font-syne), sans-serif" }}>
              Build Steps
            </h2>
            <CopyButton
              text={result.buildSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}
            />
          </div>
          <ol className="space-y-3">
            {result.buildSteps.map((step, i) => (
              <li key={i} className="flex gap-4">
                <span
                  className="flex-shrink-0 w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold"
                  style={{ background: "var(--accent-cyan-dim)", color: "var(--accent-cyan)", border: "1px solid rgba(34,211,238,0.2)", fontFamily: "var(--font-jetbrains-mono), monospace" }}
                >
                  {i + 1}
                </span>
                <span className="text-sm pt-1 leading-relaxed" style={{ color: "var(--text-secondary)" }}>{step}</span>
              </li>
            ))}
          </ol>
        </div>

        {/* Tradeoffs */}
        <div>
          <h2 className="text-base font-bold mb-4" style={{ fontFamily: "var(--font-syne), sans-serif" }}>
            Tradeoffs
          </h2>
          <ul className="space-y-2.5">
            {result.tradeoffs.map((tradeoff, i) => (
              <li
                key={i}
                className="text-sm pl-4 leading-relaxed"
                style={{ color: "var(--text-secondary)", borderLeft: "2px solid var(--border-default)" }}
              >
                {tradeoff}
              </li>
            ))}
          </ul>
        </div>

        {/* Footer CTA */}
        <div
          className="pt-8 text-center"
          style={{ borderTop: "1px solid var(--border-subtle)" }}
        >
          <p className="text-sm mb-4" style={{ color: "var(--text-tertiary)" }}>
            Generated by AI Stack Radar — architecture recommendations backed by live sentiment data.
          </p>
          <Link
            href="/generate"
            className="btn-primary px-6 py-2.5 rounded-xl text-sm inline-block"
            style={{ fontFamily: "var(--font-syne), sans-serif" }}
          >
            Generate Your Own Stack
          </Link>
        </div>
      </div>
    </div>
  );
}
