import { notFound } from "next/navigation";

export const dynamic = "force-dynamic";

interface ArchResult {
  summary: string;
  tools: Array<{ name: string; category: string; reason: string }>;
  diagram: string;
  buildSteps: string[];
  tradeoffs: string[];
}

interface SharedStack {
  id: string;
  prompt: string;
  result: ArchResult;
  createdAt: string;
}

async function getStack(id: string): Promise<SharedStack | null> {
  try {
    const { db } = await import("@/lib/db");
    const { sharedStacks } = await import("@/lib/schema");
    const { eq } = await import("drizzle-orm");

    const [stack] = await db
      .select()
      .from(sharedStacks)
      .where(eq(sharedStacks.id, id))
      .limit(1);

    if (!stack) return null;

    return {
      id: stack.id,
      prompt: stack.prompt,
      result: stack.result as ArchResult,
      createdAt: stack.createdAt.toISOString(),
    };
  } catch {
    return null;
  }
}

export default async function SharedStackPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const stack = await getStack(id);

  if (!stack) {
    notFound();
  }

  const result = stack.result;

  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <div className="mb-8">
        <p className="text-sm text-zinc-500 mb-2">Shared Stack</p>
        <h1 className="text-2xl font-bold tracking-tight">{stack.prompt}</h1>
      </div>

      <div className="space-y-8">
        <p className="text-zinc-300 text-lg">{result.summary}</p>

        <div>
          <h2 className="text-xl font-semibold mb-4">Recommended Stack</h2>
          <div className="grid gap-3">
            {result.tools.map((tool, i) => (
              <div
                key={i}
                className="p-4 border border-zinc-800 rounded-xl bg-zinc-900/50"
              >
                <div className="flex items-center gap-3 mb-1">
                  <span className="font-medium text-zinc-100">{tool.name}</span>
                  <span className="text-xs px-2 py-0.5 rounded bg-zinc-800 text-zinc-400">
                    {tool.category}
                  </span>
                </div>
                <p className="text-sm text-zinc-400">{tool.reason}</p>
              </div>
            ))}
          </div>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4">Architecture Diagram</h2>
          <div className="p-6 border border-zinc-800 rounded-xl bg-zinc-900/50 overflow-x-auto">
            <pre className="text-sm text-zinc-400">{result.diagram}</pre>
          </div>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4">Build Steps</h2>
          <ol className="space-y-3">
            {result.buildSteps.map((step, i) => (
              <li key={i} className="flex gap-3">
                <span className="flex-shrink-0 w-7 h-7 rounded-full bg-zinc-800 flex items-center justify-center text-sm font-medium text-zinc-400">
                  {i + 1}
                </span>
                <span className="text-zinc-300 pt-0.5">{step}</span>
              </li>
            ))}
          </ol>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4">Tradeoffs</h2>
          <ul className="space-y-2">
            {result.tradeoffs.map((tradeoff, i) => (
              <li
                key={i}
                className="text-zinc-400 text-sm pl-4 border-l-2 border-zinc-800"
              >
                {tradeoff}
              </li>
            ))}
          </ul>
        </div>

        <div className="pt-8 border-t border-zinc-800 text-center">
          <p className="text-zinc-500 text-sm mb-3">
            Generated by AI Stack Radar — architecture recommendations backed by live
            sentiment data.
          </p>
          <a
            href="/generate"
            className="px-6 py-2.5 bg-white text-zinc-900 rounded-lg font-medium hover:bg-zinc-200 transition-colors inline-block"
          >
            Generate Your Own Stack
          </a>
        </div>
      </div>
    </div>
  );
}
